[package]
name = "open-menu"
version = "0.1.0"
authors = ["jucasoliveira <jucas.oliveira@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-rt = "1.0"